version: "3.7"
services:
  work:
    hostname: "WORKING!"
    build:
      context: ./docker/work
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./workspace:/root/workspace
  app:
    hostname: "APP!"
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./workspace/app:/root/workspace/app
    ports:
      - "8080:8080"
